host: "0.0.0.0"
port: "8080"
certFile: ""
keyFile: ""
staticDir: "./static"
staticPath: "/static/"
healthPath: "/health"
requestTimeout: 1000  # in milliseconds
default404Handler: true
handleMethodNotAllowed: false
defaultContentType: "application/json"
