# app-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: contacts-app-service
spec:
  type: NodePort
  selector:
    app: contacts-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30007


